name: Cypress Tests
on: 
    push:
      branches: [feature/create-pipeline]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        strategy: 
            fail-fast: false
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                record: true
              env:
                CYPRESS_RECORD_KEY: d92d2c56-7343-4525-bbe3-6a608b132b11